config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/apresentacao/:name/:number', to: 'apresentation#home', as: "home"
  get '/comidas', to: "food#now", as: "food_now"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def hi
        "hello world"
    end
end

app/controllers/apresentation_controller.rb
class ApresentationController < ApplicationController
    after_action :oi_gente
    
    def home
        @name = params[:name]
        @number = params[:number].to_i 
    end


    def oi_gente
        @age = 20
    end
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
    def now

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apresentation/home.html.erb
<% @number.times do%>
    <h1 class='good-morning'>Boa Tarde, <%= @name%>, idade <%= @age%></h1>
<%  end %>
<%= link_to  "Venha Comer", food_now_path, class: "good-morning" %>
<a href="/comida">Venha Comer</a>

app/views/apresentation/lucas.html.erb
<h1>Eu sou Lucas</h1>

app/views/food/now.html.erb
<h1>Eu estou com fome</h1>
<%= link_to  "apresentação", home_path(name: "Lucas", number: 10, search: "Luc") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Aula1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= yield %>
    
</body>

</html>